@route = assets

### Create a list of images
< {%

    let productIds = client.global.get("defaultProductIds");
    let imageContent = client.global.get("defaultContent");

    request.variables.set("clients", [ // test data
        {"Content": imageContent[0],"ProductId": productIds[0], "IsShown": true, "Priority": 1},
        {"Content": imageContent[0],"ProductId": productIds[0], "IsShown": true, "Priority": 2},
        
    ])
%}

POST {{baseUrl}}/{{route}}
Content-Type: application/json

{
  "Content": "{{$.clients..Content}}",
  "ProductId": "{{$.clients..ProductId}}",
  "IsShown": {{$.clients..IsShown}},
  "Priority": {{$.clients..Priority}}
}

> {%
    // let current = request.variables.get("clients")[request.iteration()]
    // client.test(`Account ${current.lastName} has initial balance ${current.balance}`, () => {
    //     let responseBalance = jsonPath(response.body, "$.json.balance")
    //     client.assert(responseBalance == current.balance)
    // })
%}