

### CreateProduct
POST {{baseUrl}}/{{assetsPath}}/addProduct
Content-Type: application/json

{
  "Name": "Test Product"
}



### Flow_CreateProduct
POST {{baseUrl}}/{{assetsPath}}/addProduct
Content-Type: application/json

{
  "Name": "Test Product"
}
> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    if(response.status === 200) {
        console.log(response)
        client.global.set("flow-createdProductId", response.body.productID);
    }
%}