import ../GlobalVariables.http
run #Set Global Variables

### Create an image
POST {{baseUrl}}/{{assetsPath}}
Content-Type: application/json

{
  "Content": "image_base64_data"
}

### PATCH request to update an image
PATCH {{baseUrl}}/{{route}}/daa63271-80db-4ab5-9ca2-41cb7f61fab6
Content-Type: application/json

[
  { "op": "replace", "path": "/isShown", "value": false },
  { "op": "replace", "path": "/priority", "value": 5 }
]

### New test
PATCH {{baseUrl}}/{{route}}/8e04bb15-8180-4351-94ea-047e6bbb5d9b
Content-Type: application/json

[
  { "op": "replace", "path": "/ProductUUID", "value": "C5FB57C9-5634-4FBB-936F-C40D6983D044" },
  { "op": "replace", "path": "/priority", "value": 1 }
]


### Flow_PatchImageUpdateContent
< {%
    let savedFlowId = client.global.get("flow-createdImageId");
    request.variables.set("flowImageId", savedFlowId);
    
    let defaultImage2 = client.global.get("defaultContent")[1];
    request.variables.set("newImage", defaultImage2);
%}
PATCH {{baseUrl}}/{{assetsPath}}/{{flowImageId}}
Content-Type: application/json

[
  { "op": "replace", "path": "/Content", "value": "{{newImage}}" }
]

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}