import ../GlobalVariables.http
run #Set Global Variables

### PatchProductImage
@ProductID = 6f1c3cf5-c47f-4c15-8f97-12d7634800ba
@ImageID = 4e4c92b8-575a-4842-9e49-0f2931a1b185
PATCH {{baseUrl}}/{{assetsPath}}/{{ProductID}}/{{ImageID}}
Content-Type: application/json

[
  { "op": "replace", "path": "/Priority", "value": 10 }
]


### Flow_PatchProductImage
< {%
    // let productId = client.global.get("flow-createdProductId");
    let p
    ProductId = "";
    request.variables.set("productID", ProductId);

    // let savedFlowId = client.global.get("flow-createdImageId");
    let savedFlowId = "";
    request.variables.set("flowImageId", savedFlowId);
%}
PATCH {{baseUrl}}/{{assetsPath}}/{{productID}}/{{flowImageId}}
Content-Type: application/json

[
  { "op": "replace", "path": "/priority", "value": 5 }
]