import ../GlobalVariables.http
run #Set Global Variables

### AssignImageToProduct
@ProductID = 6f1c3cf5-c47f-4c15-8f97-12d7634800ba
POST {{baseUrl}}/{{assetsPath}}/{{ProductID}}/remove
Content-Type: application/json

{
    "ImageId": "50612971-cff2-4082-82f4-efdbbe1090c4"
}

### Flow_AssignImageToProduct
< {%
    let savedFlowId = client.global.get("flow-createdImageId");
    request.variables.set("flowImageId", savedFlowId);

    let savedProductId = client.global.get("flow-createdProductId");
    request.variables.set("productID", savedProductId);
%}
POST {{baseUrl}}/{{assetsPath}}/{{productID}}/add
Content-Type: application/json

{
  "ImageId": "{{flowImageId}}",
  "Priority": 1
}


