import ../CRUD/AssignProductImage.http
import ../CRUD/CreateProduct.http
import ../CRUD/CreateImage.http

//todo: make test for assigning image to non-existing product


### Create a new product
run #Flow_CreateProduct

### Create a new image
run #CreateImageWithSpecificContent

### Assign image to product
run #Flow_AssignImageToProduct