import ../GlobalVariables.http
import ../CRUD/CreateImage.http
import ../CRUD/DeleteImage.http
import ../CRUD/PatchImage.http
run #Set Global Variables



### Create image with specific ID
run #CreateImageWithSpecificContent

### Patch image with specific ID
run #Flow_PatchImageUpdateContent

//Add test to check if the image was updated

### Delete the Image again
run #DeleteImageWithSpecificId

